// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "proxy.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::Proxy;

class proxyHandler : virtual public proxyIf {
 public:
  proxyHandler() {
    // Your initialization goes here
  }

  void getPage(std::string& _return, const std::string& URL) {
    // Your implementation goes here
    printf("getPage\n");
  }

  int32_t getCachedVolume() {
    // Your implementation goes here
    printf("getCachedVolume\n");
  }

  int32_t getNetworkVolume() {
    // Your implementation goes here
    printf("getNetworkVolume\n");
  }

  int32_t getHitCount() {
    // Your implementation goes here
    printf("getHitCount\n");
  }

  int32_t getMissCount() {
    // Your implementation goes here
    printf("getMissCount\n");
  }

  void resetCounters() {
    // Your implementation goes here
    printf("resetCounters\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<proxyHandler> handler(new proxyHandler());
  shared_ptr<TProcessor> processor(new proxyProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

